---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mdape2e-ci-backend
  name: mdape2e-ci-backend
  # namespace: mdape2e-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdape2e-ci-backend
  template:
    metadata:
      labels:
        app: mdape2e-ci-backend
    spec:
      containers:
      - env:
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: apikey
              name: api-key
        image: mayadataio/ci-dashboard-postgres:mdape2e-7e9ec902
        imagePullPolicy: Always
        name: mdape2e-ci-backend
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mdape2e-ci-backend
  name: mdape2e-ci-backend-service
  # namespace: mdape2e-ci
spec:
  ports:
  - name: mdape2e-ci-backend
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mdape2e-ci-backend
  type: ClusterIP      
